# Generated by Django 5.1.7 on 2025-11-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainMeals',
            new_name='MainMeal',
        ),
    ]
