# Generated by Django 5.1.7 on 2025-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_mainmeals_mainmeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmeal',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
