# Generated by Django 5.1.7 on 2025-11-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingPlatters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='mainmeal',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='saladmeal',
            old_name='name',
            new_name='title',
        ),
    ]
