# Generated by Django 5.1.7 on 2025-11-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sharingplatters_rename_name_drink_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharingPlatters',
            new_name='SharingPlatter',
        ),
    ]
