# Generated by Django 5.1.7 on 2025-11-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_sharingplatters_sharingplatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingplatter',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
