# Generated by Django 5.1.7 on 2025-11-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_sharingplatter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingplatter',
            name='description',
            field=models.TextField(blank=True, default='No Description Yet For This Platter', max_length=200, null=True),
        ),
    ]
