# Generated by Django 5.1.7 on 2025-11-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_sharingplatter_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('main', 'Main Meal'), ('salad', 'Salad'), ('drink', 'Drink'), ('sharing', 'Sharing Platter')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='MainMeal',
        ),
        migrations.DeleteModel(
            name='SaladMeal',
        ),
        migrations.DeleteModel(
            name='SharingPlatter',
        ),
    ]
