# Generated by Django 5.1.7 on 2025-12-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_product_options_alter_product_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
