# Generated by Django 6.0.1 on 2026-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_description', models.TextField(blank=True, max_length=200, null=True)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dish_photo', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('dish_category', models.CharField(choices=[('main', 'Main Plates'), ('pasta', 'Pasta & Hand-folded'), ('bowl', 'Bowls & Greens'), ('dessert', 'Desserts')], max_length=20)),
            ],
            options={
                'ordering': ['dish_category'],
            },
        ),
    ]
