# Generated by Django 6.0.1 on 2026-05-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dish_photo',
            field=models.URLField(),
        ),
    ]
